# Generated by Django 3.0.5 on 2020-12-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hashCode',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
